import logging

from fastapi import APIRouter, Depends
from weaviate.classes.query import Filter

from app.dependencies import get_recommend_pipeline, get_weaviate_client
from app.schemas import RecommendRequest, RecommendResponse

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/recommend", tags=["Recommend"])


@router.post("", response_model=RecommendResponse)
def recommend(
    body: RecommendRequest,
    pipeline=Depends(get_recommend_pipeline),
    weaviate_client=Depends(get_weaviate_client),
) -> RecommendResponse:
    """
    Return top-k personalized product recommendations.

    **Warm users** (with prior interactions stored in Redis): recommendations
    are generated by querying the user's Personal MLP embedding space with
    their EMA user vector, then re-ranking candidates by Euclidean distance.

    **Cold users** (no Redis state): falls back to item-to-item KNN from the
    seed `article_id` using the global CLIP embedding catalog.

    The `user_id` field drives personalization — omit it (or use a new ID)
    to get cold-start recommendations.
    """
    user_id = body.user_id or "cold_user"

    res = pipeline.recommend(
        session_id=user_id,
        seed_article_id=body.article_id,
        k=body.k,
    )
    
    rec_ids = res.get("article_ids", [])
    has_personalization = len(rec_ids) > 0

    recs_hydrated = []
    if rec_ids:
        # Hydration: Fetch prod_name and image_url from Weaviate's Product collection
        collection = weaviate_client.collections.get("Product")
        objects = collection.query.fetch_objects(
            filters=Filter.by_property("article_id").contains_any(rec_ids),
            limit=len(rec_ids)
        ).objects

        # Build a fast O(1) lookup map
        meta_lookup = {}
        for obj in objects:
            aid = obj.properties.get("article_id")
            meta_lookup[aid] = {
                "prod_name": obj.properties.get("prod_name", "Unknown Product"),
                "image_url": obj.properties.get("image_url", ""),
            }

        # Reconstruct list maintaining the exact order generated by the Stage-2 Reranker
        for i, aid in enumerate(rec_ids):
            # Generate a mock score representing descending confidence
            score = round(1.0 - (i * (1.0 / len(rec_ids))), 3) if len(rec_ids) > 0 else 1.0
            meta = meta_lookup.get(aid, {"prod_name": "Unknown Product", "image_url": ""})
            recs_hydrated.append({
                "article_id": aid,
                "prod_name": meta["prod_name"],
                "image_url": meta["image_url"],
                "score": score
            })

    return RecommendResponse(
        recommendations=recs_hydrated,
        user_id=user_id,
        personalized=has_personalization,
    )
